
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    #pod 에 설정되는 컨테이너 설정
    spec:
      imagePullSecrets:
        # values.yaml 파일에 imagePullSecret이라는 데이터가 있다면 실행
        # - name : .(현재 반복중인 항목) | quote(인용부호로 감싸서 적용)
        # .Values : 해당차트 꺼
        # $.Values : 전역꺼
{{/*        {{- if $.Values.imagePullSecrets}}*/}}
{{/*          {{- range $.Values.imagePullSecrets}}*/}}
{{/*        - name: {{ . | quote}}*/}}
{{/*          {{- end}}*/}}
{{/*          {{- end}}*/}}
        - name: ecr-secret
      containers:
        - name: rabbitmq
          image: {{ .Values.image}}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.service.messagingPort }}
            - containerPort: {{ .Values.service.uiPort }}
          env:
            {{- range $key, $value := .Values.env}}
            - name: {{ $key }}
              value: "{{$value}}"
            {{- end}}


