apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-boot
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  type: NodePort